### ISSUE TITLE
Lodash version < 4.17.12

### ISSUE THREAD

**Issue by pbrose** [SAP/webide-client-tools#111]
Hi All,

This library in it's latest released version (v 3.0.3)  uses lodash v4.17.11. Please can you urgently release a patch using lodash >= v 4.17.12 so that the latest npm versions will not fail npm audit and also other vulnerability-check tools don't fail the webide-client-tools library?

In particular, this very severe issue is currently included in webide-client-tools v3.0.3: https://www.npmjs.com/advisories/1065
Cheers

**Comment by pbrose** [comment]
Any update?

**Comment by pbrose** [comment]
bump

**Comment by idogoren** [comment]
Thanks for reporting the issue. We have an open PR on that:
https://github.com/SAP/webide-client-tools/pull/109

**Comment by idogoren** [comment]
A new version was released (3.0.4) with this fix.
