### ISSUE TITLE
Unable to fetch data from ES5 in WebIDE, based on folder location.

### ISSUE THREAD

**Issue by vikasgith** [SAP/webide-client-tools#141]
Unable to fetch data from ES5 in WebIDE, based on folder location.
Hi,
I am using trial verison of WebIDE.
My url is 
https://webidecp-s0022047769trial.dispatcher.hanatrial.ondemand.com/

I have downloaded code from folder 
https://github.com/SAP/openSAP-ui5-course/tree/ui51/w2u5 in my WebIDE workspace folder w2u5b,
When I execute Workspace/w2u5b/webapp/index.html file from here data is fetched from ES5 system
![WebIDE-Working](https://user-images.githubusercontent.com/39696669/94817869-1c476080-041b-11eb-9bde-116f5fd200ca.png)

Corresponding URL is https://webidetesting0652960-s0022047769trial.dispatcher.hanatrial.ondemand.com/destinations/ES5/sap/opu/odata/IWBEP/GWSAMPLE_BASIC/$metadata?sap-language=EN

Now I download this code from https://github.com/SAP/openSAP-ui5-course/tree/ui51/w2u5 to another folder .
 Workspace/TestPosition/w2u5/webapp.index.html

 

![WebIDE-Not-Working](https://user-images.githubusercontent.com/39696669/94817907-26695f00-041b-11eb-95f4-1711d614d91f.png)

 
https://webidetesting6465275-s0022047769trial.dispatcher.hanatrial.ondemand.com/destinations/ES5/sap/opu/odata/IWBEP/GWSAMPLE_BASIC/$metadata?sap-language=EN

Only difference is non working code is one folder additional below workspace compared to working code.
Also the server number has changed.

Is this a non issue , i.e. WebIDE is unable to fetch data when folder level changes.

**Comment by gadisn** [comment]
Hi,
The 'server number' diff you get is OK - this part of the hsot in a preview URL is generated.
Projects in web ide are typically at the root, and not under sub folders.

Regards,
Gadi
